### ISSUE TITLE
Give warnings when we are not confident in an automatic fix (e.g., "bad header" matches closest to "the real deal" but is not at all similar enough to change it to that)

### ISSUE THREAD

**Issue by dalpal07** [dalpal07/StudAI#19]

**Comment by dalpal07** [comment]
Warnings will need to be revisited when the cleaning process is more defined

**Comment by dallinburnedu** [comment]
Also may need some work on closest matching one, sometimes the headers get messed up just because the system recognizes it as something else.

**Comment by dalpal07** [comment]
match_header_value.js at line 40 should only pass in header values that have not been matched.
