### ISSUE TITLE
rearrange

### ISSUE THREAD

**Issue by dalpal07** [dalpal07/StudAI#31]

**Comment by CollinMorrison** [comment]
@dalpal07 By this do you mean existing rows in the uploaded spreadsheet? If not, the only thing to add to the web app functionality would be to be able to rearrange rows right?

**Comment by dalpal07** [comment]
@CollinMorrison this is meant for rearranging rows in the template created by the user

**Comment by CollinMorrison** [comment]
@dalpal07 Sweet, are you good if I start on this or would it be more useful for me to work on something else? Not sure where you're at

**Comment by dalpal07** [comment]
@CollinMorrison Yeah, go ahead and start on this! You're welcome to any of the tasks right now. Feel free to text me with any questions and we can collaborate
