### ISSUE TITLE
Recognize number spaces vs word spaces

### ISSUE THREAD

**Issue by dallinburnedu** [dalpal07/StudAI#41]
It would be awesome to differentiate between number spaces and word spaces. On top of that, having it fill empty number places with zero would be cool.

**Comment by dallinburnedu** [comment]
The only other thing specific to word spaces would be to recognize if there is a space at the end of the last word and delete it. That's all I can think of.

**Comment by dalpal07** [comment]
Okay, sounds good! I'll try to do this issue next.
