### ISSUE TITLE
Memory

### ISSUE THREAD

**Issue by dallinburnedu** [dalpal07/StudAI#51]
Remember past uploads and save the requirements so you can run the same upload over and over again. Also could remember past data uploaded so that you could make the available values all of one previously uploaded column

**Comment by dalpal07** [comment]
@dallinburnedu if you could save templates, would this accomplish the whole purpose?

**Comment by dalpal07** [comment]
then it would remember each header, whether they are required or not, their type, and their acceptable values

**Comment by dalpal07** [comment]
- [ ] Get a database set up
- [ ] Implement authentication and accounts
- [ ] Allow templates to be saved
- [ ] Remember previously uploaded column values
